# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.srcs/sources_1/ip/commandFIFO/commandFIFO.xci
# IP: The module: 'commandFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.gen/sources_1/ip/commandFIFO/commandFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'commandFIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.gen/sources_1/ip/commandFIFO/commandFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'commandFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.srcs/sources_1/ip/commandFIFO/commandFIFO.xci
# IP: The module: 'commandFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.gen/sources_1/ip/commandFIFO/commandFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'commandFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jblan/Documents/GitHub/Graphics-Processor-Senior-Project/Project Files/Senior-Project/Senior-Project.gen/sources_1/ip/commandFIFO/commandFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'commandFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
